/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'alec' at '18/04/16 07:07' with Gradle 2.4
 *
 * @author alec, @date 18/04/16 07:07
 */
public class Card implements Comparable<Card> {

    private int faceValue;
    private Suit suit;

    public Card(int faceValue, Suit suit) {
        this.faceValue = faceValue;
        this.suit = suit;
    }

    public int getFaceValue() {
        return faceValue;
    }

    public Suit getSuit() {
        return suit;
    }

    @Override
    public int compareTo(Card other) {
        if(suit.compareTo(other.getSuit()) == 0) {
            return faceValue - other.getFaceValue();
        }
        return suit.compareTo(other.getSuit());
    }

    public String toString() {
        return String.format("Suit: %s, value %d", this.suit, this.faceValue);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

        Card card = (Card) o;

        if (faceValue != card.faceValue) return false;
        return suit == card.suit;

    }

    @Override
    public int hashCode() {
        int result = faceValue;
        result = 31 * result + (suit != null ? suit.hashCode() : 0);
        return result;
    }
}
