/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'alec' at '18/04/16 07:07' with Gradle 2.4
 *
 * @author alec, @date 18/04/16 07:07
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
